name: Send Morning Whopper Email

on:
  schedule:
    # Rulează la ora 06:00 UTC în fiecare zi (aprox. 08:00 ora României)
    - cron: '0 6 * * *'
  workflow_dispatch: # Acest buton îți permite să testezi manual oricând

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Python script
        env:
          # Aici conectăm secretele tale de pe GitHub cu scriptul
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL1: ${{ secrets.RECEIVER_EMAIL1 }}
          RECEIVER_EMAIL2: ${{ secrets.RECEIVER_EMAIL2 }}
          RECEIVER_EMAIL3: ${{ secrets.RECEIVER_EMAIL3 }}
          RECEIVER_EMAIL4: ${{ secrets.RECEIVER_EMAIL4 }}
        run: python SMTP_Sending.py